name: Deploy on Houseplants

on:
  push:
    branches:
      - main-fuckthis

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{secrets.TS_OAUTH_ID}}
          oauth-secret: ${{secrets.TS_OAUTH_SECRET}}
          tags: tag:ci
          use-cache: "true"

      - name: Deploy to Houseplants
        shell: bash
        run: |
          # Add the Tailscale IP of your VPS
          TAILSCALE_IP="houseplants" # Replace with your VPS Tailscale IP

          # SSH into the VPS and deploy
          ssh -o StrictHostKeyChecking=no "root@${TAILSCALE_IP}" /opt/sites/ivy.rs/deploy.sh